-- CreateTable
CREATE TABLE "settings" (
    "id" TEXT NOT NULL,
    "retell_api_key" TEXT,
    "retell_agent_id" TEXT,
    "retell_from_number" TEXT,
    "apollo_api_key" TEXT,
    "proxycurl_api_key" TEXT,
    "openai_api_key" TEXT,
    "openai_model" TEXT DEFAULT 'gpt-4o-mini',
    "twilio_account_sid" TEXT,
    "twilio_auth_token" TEXT,
    "twilio_from_number" TEXT,
    "calendly_access_token" TEXT,
    "calendly_event_type_uri" TEXT,
    "gmail_connected" BOOLEAN NOT NULL DEFAULT false,
    "gmail_refresh_token" TEXT,
    "gmail_email_address" TEXT,
    "call_start_hour" INTEGER NOT NULL DEFAULT 9,
    "call_end_hour" INTEGER NOT NULL DEFAULT 18,
    "calls_per_hour_limit" INTEGER NOT NULL DEFAULT 10,
    "call_gap_seconds" INTEGER NOT NULL DEFAULT 30,
    "max_retry_attempts" INTEGER NOT NULL DEFAULT 3,
    "voicemail_on_attempt" INTEGER NOT NULL DEFAULT 2,
    "max_emails_per_day" INTEGER NOT NULL DEFAULT 100,
    "email_send_start_hour" INTEGER NOT NULL DEFAULT 9,
    "email_send_end_hour" INTEGER NOT NULL DEFAULT 18,
    "email_gap_seconds" INTEGER NOT NULL DEFAULT 10,
    "google_service_account_key_path" TEXT,
    "connected_sheet_url" TEXT,
    "connected_sheet_name" TEXT,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "settings_pkey" PRIMARY KEY ("id")
);
